// flow-typed signature: db89f27855614dacea4545a1d14ca065
// flow-typed version: <<STUB>>/react-native-upload-image-expo_vgithub:br4in3x/react-native-upload-image-expo/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-upload-image-expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-upload-image-expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-upload-image-expo/example/App' {
  declare module.exports: any;
}

declare module 'react-native-upload-image-expo/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-upload-image-expo/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-upload-image-expo/flow-typed/npm/eslint-config-airbnb_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-upload-image-expo/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-upload-image-expo/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-upload-image-expo/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-upload-image-expo/flow-typed/npm/expo_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-upload-image-expo/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'react-native-upload-image-expo/flow-typed/npm/jest-expo_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-upload-image-expo/flow-typed/npm/prop-types_v15.x.x' {
  declare module.exports: any;
}

declare module 'react-native-upload-image-expo/flow-typed/npm/react-native_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-upload-image-expo/flow-typed/npm/react-native-scripts_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-upload-image-expo/flow-typed/npm/react-test-renderer_v16.x.x' {
  declare module.exports: any;
}

declare module 'react-native-upload-image-expo/flow-typed/npm/uuid_v3.x.x' {
  declare module.exports: any;
}

declare module 'react-native-upload-image-expo/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-upload-image-expo/example/App.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo/example/App'>;
}
declare module 'react-native-upload-image-expo/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'react-native-upload-image-expo/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'react-native-upload-image-expo/flow-typed/npm/eslint-config-airbnb_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo/flow-typed/npm/eslint-config-airbnb_vx.x.x'>;
}
declare module 'react-native-upload-image-expo/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'react-native-upload-image-expo/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module 'react-native-upload-image-expo/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'react-native-upload-image-expo/flow-typed/npm/expo_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo/flow-typed/npm/expo_vx.x.x'>;
}
declare module 'react-native-upload-image-expo/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'react-native-upload-image-expo/flow-typed/npm/jest-expo_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo/flow-typed/npm/jest-expo_vx.x.x'>;
}
declare module 'react-native-upload-image-expo/flow-typed/npm/prop-types_v15.x.x.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo/flow-typed/npm/prop-types_v15.x.x'>;
}
declare module 'react-native-upload-image-expo/flow-typed/npm/react-native_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo/flow-typed/npm/react-native_vx.x.x'>;
}
declare module 'react-native-upload-image-expo/flow-typed/npm/react-native-scripts_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo/flow-typed/npm/react-native-scripts_vx.x.x'>;
}
declare module 'react-native-upload-image-expo/flow-typed/npm/react-test-renderer_v16.x.x.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo/flow-typed/npm/react-test-renderer_v16.x.x'>;
}
declare module 'react-native-upload-image-expo/flow-typed/npm/uuid_v3.x.x.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo/flow-typed/npm/uuid_v3.x.x'>;
}
declare module 'react-native-upload-image-expo/index' {
  declare module.exports: $Exports<'react-native-upload-image-expo'>;
}
declare module 'react-native-upload-image-expo/index.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo'>;
}
declare module 'react-native-upload-image-expo/types.js' {
  declare module.exports: $Exports<'react-native-upload-image-expo/types'>;
}
